### ISSUE TITLE
roots wordpress inside timber theme folder

### ISSUE THREAD

**Issue by avblink** [timber/starter-theme#166]
Just wanted to check why is there 'wordpress' directory from 'roots' inside timber theme folder?
Was it meant to be installed in the parent wordpress folder?
Is it used for something else?
It's just adding an extra bunch of files that already exist in the parent root directory?

Thank you.

**Comment by szepeviktor** [comment]
Thank you for your report.

> is there 'wordpress' directory from 'roots' inside timber theme folder?

That is for testing.

Try `composer create-project timber/starter-theme:2.x-dev --no-dev`

**Comment by avblink** [comment]
If I run your command above, then it creates the starter-theme as expected.
However if I cd into the starter-theme folder and run 'composer install', it will download the wordpress folder.
You'd run 'composer install' to install other plugins if you're managing them via composer.

**Comment by szepeviktor** [comment]
> However if I cd into the starter-theme folder

Please try the production command: `composer install --no-dev`

**Comment by gchtr** [comment]
If you run `composer install`, the development dependencies listed under `require-dev` will also be installed. There are dependencies in there that are used for PHPUnit tests. That `wordpress` folder is used for these **temporary tests**. It’s not required for your WordPress installation or the starter theme to run.

https://github.com/timber/starter-theme/blob/c116aea47525f2412d54430088c81fa93b0f045b/composer.json#L41-L48

Specifically, [WordBless](https://github.com/Automattic/wordbless) installs WordPress into the folder that is specified in 
https://github.com/timber/starter-theme/blob/c116aea47525f2412d54430088c81fa93b0f045b/composer.json#L55

If you don’t want to use testing, you can remove `automattic/wordbless` and `yoast/wp-test-utils` from **composer.json** and as well as the `extra` section:

https://github.com/timber/starter-theme/blob/c116aea47525f2412d54430088c81fa93b0f045b/composer.json#L49

Since this is a starter theme, we add some defaults to get you started. But you’re not required to use them. You can remove stuff you don’t need.

**Comment by avblink** [comment]
Thank you very much for all the info.

The solutions, as you said earlier, to run production composer install.

`composer install --no-dev `

Brilliant starter theme. Thank you.
